name: Deploy
run-name: Deploy on ${{ github.head_ref }} for ${{ github.event.pull_request.title }}
on:
  push:
    branches:
      - dev
      - 'release/*'
      - main

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || github.ref_name == 'dev' && 'development' || 'staging' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print GitHub context
        run: echo "${{ toJson(github) }}"
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --pwa-strategy=none

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Sync files to S3
        run: aws s3 sync build/web s3://${{ vars.S3_BUCKET_NAME }}

      - name: Create CloudFront invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"